version: "3"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres-prod
    environment:
      POSTGRES_PASSWORD: despertar2024
      POSTGRES_USER: growdev
      POSTGRES_DB: despertar
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - growdev

  db_test:
    image: postgres
    restart: always
    container_name: postgres-test
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      POSTGRES_PASSWORD: test2024
      POSTGRES_USER: test
      POSTGRES_DB: test_app
    ports:
      - 5433:5432
    networks:
      - growdev

  # db:
  #   image: mysql/mysql-server:latest
  #   container_name: mysql-dev
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: despertar
  #     MYSQL_ROOT_PASSWORD: despertar2024
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - mysql-volume:/var/lib/mysql
  #   networks:
  #     - growdev

  # db_test:
  #   image: mysql/mysql-server:latest
  #   container_name: mysql-test
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: test_despertar
  #     MYSQL_ROOT_PASSWORD: test_db
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - '3307:3306'
  #   networks:
  #     - growdev

networks:
  growdev:
    driver: bridge

volumes:
  postgres:
  # mysql-volume:
  #   driver: local